### ISSUE TITLE
boto3_session seems to error, possibly because Okta SSO or new aws cli version.

### ISSUE THREAD

**Issue by mprinvale** [jimzucker/aws-forecast#5]
Running AWS SSO managed through Okta to get credentials and adding them to .aws/credentials file and manually running get_forecast.py with appropriate flags produces the following errors. Lambda is expected.

$ python3 get_forecast.py --profile redacted_AWSAdministratorAccess --type FORECAST
INFO:root:Not running as lambda
ERROR:root:Cannot connect to boto3
ERROR:root:Cannot connect to Cost Explorer with boto3

Will look into some sort of SSO or possible aws version issue but if any ideas would be helpful. 

**Re-create:**
1. Login to SSO to get new credentials
2. Add new creds to ~/.aws/credentials files
3. export new creds to ensure term session is up-to-date
4. Run python3 get_forecast.py --profile redacted_AWSAdministratorAccess --type FORECAST

aws --version
aws-cli/2.0.26 Python/3.7.4 Darwin/19.6.0 botocore/2.0.0dev30

**Comment by jimzucker** [comment]
@mprinvale Please check the IAM role for the credentials and ensure they have access to Cost Explorer, see the settings in this link: https://github.com/jimzucker/aws-forecast/blob/master/LAMBDA_README.md

Note: the messages regarding Lambda is INFO, it is not an ERROR.
